### ISSUE TITLE
Rework inclusion handling

### ISSUE THREAD

**Issue by aaronmondal** [eomii/rules_ll#1]
1. Quoted includes and angle includes need to be clearly separated. (`-iquote`, `-isystem`, `-I`, `-idirafter` `-isystem-after`).
2. There should be no implicit header includes. If something uses an unusual include path it should be specified manually. We should adhere to [the C++ standard](https://en.cppreference.com/w/cpp/preprocessor/include).
3. There should be a mechanism similar to `strip_prefix` in `rules_cc`. Otherwise we have to manually specify `includes` for external repositories. There were reasons for not implementing `strip_prefix` like in `rules_cc`. I will post an update when I remember the details. Currently, the compiler is invoked at the top-level of the action sandbox. If we were to move it into the build subdirectory within that sandbox we will need to change the way inclusions of external headers are handled (maybe prefix with `../../` or something like that).
4. Extra care needs to be taken that system headers do not accidentally include library headers named like system headers. This is an issue arising from wrong include order.

**Comment by neqochan** [comment]
`(transitive_)(relative_)(angled_)includes` now handle `-iquote` and `-I`. We have absolute and workspace-relative includes working, but cross-workspace includes are missing. This is particularly relevant for Projects building on top of LLVM.

We need to be able to reference LLVM and Clang headers from outside the `@llvm-project` workspace. Since the current implementation uses `rules_cc` for these targets we need some sort of compatibility layer. Either `rules_ll` must understand `cc_library` targets better, or we add `ll_*` targets to the existing `cc_*` overlay.

We did not encounter a need for `-idirafter`, `-isystem` and `-isystem-after`, so this is postponed.

**Comment by aaronmondal** [comment]
After adding module support we get some unwanted warnings in precompilation steps regarding `unused -iquote...`. I'm also considering whether we want to change the APIs to have finer-grained control regarding transitivity. Something like
```
attr
public_attr
transitive_attr
```
where `public_attr` is only made available to direct dependencies and `transitive_attr` is available to all downstream dependencies in the build graph. We need to be careful not to bloat the user interface for `ll_library` though :sweat_smile:

**Comment by aaronmondal** [comment]
We now removed all `transitive_*` attributes in favor of `exposed_*` attributes which don't carry dependencies transitively. I think this is good for now. We can create another issue if this needs another rework.
