### ISSUE TITLE
Linking  in WSL uses system libraries

### ISSUE THREAD

**Issue by mimed95** [eomii/rules_ll#21]
When attempting to adjust linking paths of libraries such as OpenSSL or libcrypto under WSL Ubuntu 22.04 with the "-L" flag the build will use the system libraries instead of the provided ones by the development environment.

**Comment by aaronmondal** [comment]
Using `-L` for paths like `/usr/lib` would probably override all the nix dependencies, potentially linking incompatible libc etc. As temporary workaround I think passing the explicit path to nonhermetic dependencies in `link_flags` should work.

Technically the current behavior is WAI, but I can see how this can be confusing. I've added extensibility for the flakes so that project-specific dependencies can be loaded via the nix store.

**Comment by aaronmondal** [comment]
Should be resolved by https://github.com/eomii/rules_ll/commit/e19d31f9aa5e12837397da1a5bfd392ce3e3f077 and https://github.com/eomii/rules_ll/commit/70da30682c3bec814fead33a156fb830046fad42.
