### ISSUE TITLE
rules_ll fails if gcc is used to build the Clang/LLVM based toolchain from upstream

### ISSUE THREAD

**Issue by JannisFengler** [eomii/rules_ll#7]
One of the main goals of rules_ll is to build a Clang/LLVM based toolchain from upstream. This should work with Clang and GCC. 
One error occurs when running the examples with GCC as default compiler:
> error: zlib.h: no such file or directory
Which can be fixed with installing the **libz-dev** package. 

After installing the missing headers, the build fails with following error message:  

> ERROR: /root/.cache/bazel/_bazel_root/79c7c71f78facf0e35780b9a06528730/external/@rules_ll.override.llvm_project_overlay.llvm-project/llvm/BUILD.bazel:164:11: Compiling llvm/lib/Support/Process.cpp [for tool] failed: (Exit 1): gcc failed: error executing command (from target @@rules_ll.override.llvm_project_overlay.llvm-project//llvm:Support) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 70 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> In file included from external/@rules_ll.override.llvm_project_overlay.llvm-project/llvm/lib/Support/Process.cpp:107:
> external/@rules_ll.override.llvm_project_overlay.llvm-project/llvm/lib/Support/Unix/Process.inc: In static member function 'static size_t llvm::sys::Process::GetMallocUsage()':
> external/@rules_ll.override.llvm_project_overlay.llvm-project/llvm/lib/Support/Unix/Process.inc:93:20: error: aggregate 'llvm::sys::Process::GetMallocUsage()::mallinfo2 mi' has incomplete type and cannot be defined
>    93 |   struct mallinfo2 mi;
>       |                    ^~
> external/@rules_ll.override.llvm_project_overlay.llvm-project/llvm/lib/Support/Unix/Process.inc:94:10: error: '::mallinfo2' has not been declared
>    94 |   mi = ::mallinfo2();
>       |          ^~~~~~~~~
> Target //format_example:format_example failed to build
> 

The system is Ubuntu 20.04.4 LTS, the GCC version is 9.4.0

**Comment by aaronmondal** [comment]
Zlib was initially disabled, but we enabled it by default since some operating systems use zlib compressed debug sections in glibc or are using zlib compression to compress glibc itself. We already have zlib as external dependency in the [bazel-eomii-registry](https://github.com/eomii/bazel-eomii-registry). We will add this to the dependencies for rules_ll, so that the manual zlib installation step becomes obsolete.

The other error comes from older glibc versions that don't support malloc2. I think we can fix this by using platform detection to conditionally disable [this patch](https://github.com/eomii/rules_ll/blob/main/patches/mallinfo2_patch.diff) that is used here: https://github.com/eomii/rules_ll/blob/b33741f99a6cc6b31f049f4df6ed09062c6fe470/ll/extensions.bzl#L118 for older glibc versions.

**Comment by neqochan** [comment]
51d4702422dd3531f49f5e2d183da0781fa63d5e should fix the zlib issue this also removes an unnecessary terminfo dependency.

Regarding mallinfo2, the old mallinfo was bugged. So instead instead of adding backwards compatability, added some system requirements in e11cb8520140b85f4d733a979369d3259ae4e0fd to warn against using old systems 😂

The changes will be available in version `20220722.0`.

**Comment by JannisFengler** [comment]
https://github.com/eomii/rules_ll/commit/51d4702422dd3531f49f5e2d183da0781fa63d5e fix it on my machine. The mallinfo2 issue don't occurs on Ubuntu 22.05 (with GLIBC 2.35)🥳
