### ISSUE TITLE
 ld.lld is unable to find libraries

### ISSUE THREAD

**Issue by JannisFengler** [eomii/rules_ll#9]
ld.lld is unable to find libraries when building with Ubuntu 22.04 and gcc 11.2.0. 

> ERROR: /home/ubuntu/rules_ll/examples/format_example/BUILD.bazel:3:10: LlLinkExecutable format_example/format_example failed: (Exit 1): ld.lld failed: error executing command (from target //format_example:format_example) bazel-out/k8-fastbuild/bin/external/@rules_ll.override/ll/ld.lld --color-diagnostics '-dynamic-linker=/lib64/ld-linux-x86-64.so.2' --lto-O3 --pie --nostdlib -L/usr/lib64 -lm -ldl -lpthread -lc ... (remaining 11 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> ld.lld: error: unable to find library -lm
> ld.lld: error: unable to find library -ldl
> ld.lld: error: unable to find library -lpthread
> ld.lld: error: unable to find library -lc
> Target //format_example:format_example failed to build

I set the symlinks for crt*.o and Scrt*.o manual, but all the libraries are in /usr/lib/x86_64-linux-gnu and not in /usr/lib64 . 
Maybe it makes sense to to set /usr/lib/x86_64-linux-gnu the default?

**Comment by neqochan** [comment]
The issue is that ubuntu based distros use `/usr/lib/x86_64-linux-gnu` instead of the usual `/usr/lib64`. On these distros a symlink won't work, because `/usr/lib64` is already populated with at symlink to the dynamic linker.

We definitely should not add the `*-linux-gnu` path to the defaults, as this is specific to ubuntu and not used anywhere else. Adding this to default search paths would pollute builds for all other distros. We need to find a way to still query this on ubuntu though.

**Comment by neqochan** [comment]
Rewrote logic around symbolic link detection. This includes now querying the local library path using `/etc/os-release`. This also obsoletes any manual setting of symbolic links.

`20220722.1` will be the first release containing these changes. Please let me know if things work correctly now.

**Comment by neqochan** [comment]
`20220722.1` was faulty. Updated to `20220723.0`.

**Comment by neqochan** [comment]
`20220723.0` was also faulty. Updated to `20220723.1` :rofl:

**Comment by neqochan** [comment]
Solved with `20220723.1`.
